### ISSUE TITLE
20-way classification on MiniImageNet h5 error

### ISSUE THREAD

**Issue by AmirooR** [lucfra/FAR-HO#10]
Hi @lucfra ,
I ran the same code with CLASSES=20 with your h5 files. However, I get an error. Here is the code:
```python
from far_ho.examples.hyper_representation import train, mini_imagenet_model

if __name__ == '__main__':
  CLASSES = 20
  SHOTS = 1
  META_BATCH_SIZE = 4
  from experiment_manager.datasets import load
  mini_imagenet = load.meta_mini_imagenet(std_num_classes=CLASSES,
                                          std_num_examples=(SHOTS*CLASSES, 15*CLASSES), h5=True)
  res = train(mini_imagenet, 'test', mini_imagenet_model, T=1, print_every=1000, MBS=META_BATCH_SIZE, n_episodes_testing=150, patience=20)
```

The error is related to dataset. 
```
Traceback (most recent call last):
  File "run_hyper.py", line 11, in <module>
    res = train(mini_imagenet, 'maml', mini_imagenet_model, T=1, print_every=500, MBS=META_BATCH_SIZE, n_episodes_testing=150, patience=20)
  File "/home/amir/.conda/envs/farho/lib/python3.5/site-packages/far_ho/examples/hyper_representation.py", line 245, in train
    farho.run(T[0], trfd, vfd)  # one iteration of optimization of representation variables (hyperparameters)
  File "/home/amir/.conda/envs/farho/lib/python3.5/site-packages/experiment_manager/savers/records.py", line 72, in _saver_wrapped
    self._execute_save(res, *args, **kwargs)
  File "/home/amir/.conda/envs/farho/lib/python3.5/site-packages/experiment_manager/savers/records.py", line 125, in _execute_save
    super()._execute_save(res, *args, **kwargs)
  File "/home/amir/.conda/envs/farho/lib/python3.5/site-packages/experiment_manager/savers/records.py", line 98, in _execute_save
    _res=res)
  File "/home/amir/.conda/envs/farho/lib/python3.5/site-packages/experiment_manager/savers/save_and_load.py", line 535, in save
    rss = _compute_value(pt, save_dict)
  File "/home/amir/.conda/envs/farho/lib/python3.5/site-packages/experiment_manager/savers/save_and_load.py", line 516, in _compute_value
    if callable(pt[1]) else _tf_run_catch_not_initialized(pt, _partial_save_dict)
  File "/home/amir/.conda/envs/farho/lib/python3.5/site-packages/experiment_manager/savers/save_and_load.py", line 492, in _maybe_call
    _out = _method()
  File "/home/amir/.conda/envs/farho/lib/python3.5/site-packages/far_ho/examples/hyper_representation.py", line 157, in <lambda>
    'FLAT', lambda: accs_and_errs(metasets),
  File "/home/amir/.conda/envs/farho/lib/python3.5/site-packages/far_ho/examples/hyper_representation.py", line 133, in accs_and_errs
    for _d in meta_dataset.generate(n_episodes_testing, batch_size=MBS, rand=0):
  File "/home/amir/.conda/envs/farho/lib/python3.5/site-packages/experiment_manager/datasets/structures.py", line 265, in generate
    yield self.generate_batch(batch_size, rand=rand, *args, **kwargs)
  File "/home/amir/.conda/envs/farho/lib/python3.5/site-packages/experiment_manager/datasets/structures.py", line 271, in generate_batch
    return [self.generate_datasets(rand, *args, **kwargs) for _ in range(batch_size)]
  File "/home/amir/.conda/envs/farho/lib/python3.5/site-packages/experiment_manager/datasets/structures.py", line 271, in <listcomp>
    return [self.generate_datasets(rand, *args, **kwargs) for _ in range(batch_size)]
  File "/home/amir/.conda/envs/farho/lib/python3.5/site-packages/experiment_manager/datasets/load.py", line 400, in generate_datasets
    random_classes = rand.choice(list(clss.keys()), size=(num_classes,), replace=False)
  File "mtrand.pyx", line 1437, in mtrand.RandomState.choice (numpy/random/mtrand/mtrand.c:17481)
ValueError: Cannot take a larger sample than population when 'replace=False'
```

Could you please let me know how to fix this?

**Comment by lucfra** [comment]
Hi @AmirooR , 

I've updated `experiment_package` and run your code, and it should work fine.
It's possible that with the previous version there was some problem; sorry for that.
Try to install the new one!

Cheers, 
Luca

**Comment by AmirooR** [comment]
Hi @lucfra ,

Thanks for the response and sorry for multiple queries. Did you update this [ExperimentManager](https://github.com/lucfra/ExperimentManager) package? It seems the last commit is a bit old.

Cheers,
Amir

**Comment by lucfra** [comment]
Yes yes. 
It is just that probably I forgot time ago to push the changes... earlier I did!
Let me know if you still have troubles.

Cheers 
Luca

**Comment by AmirooR** [comment]
It is not updated yet ...

Cheers,
Amir

**Comment by lucfra** [comment]
The version of ExperimentManager package that is now on Github is the "updated" one (even though actually the last commit is 1 month old..) . Previously there was an older version because I probably forgot to push the changes on Github.
Sorry; maybe what I wrote was unclear..

So, with this version I run your code on my computer and it works... Let me know if it works also for you.

Luca

**Comment by AmirooR** [comment]
I am using the updated version and the problem is still there. The problem is that it uses 16 classes for meta validation but the number of classes is 20 and it cannot sample them in `datasets.load.py` line 400.

Best,
Amir

**Comment by lucfra** [comment]
Yes you're right; that's the problem!
In that case the code fails, yes.. You could modify the code so that it can sample already used classes, but I belive it would not really make sense..  
Well, I guess if you want to try 20-ways on (Mini)Imagenet you should create a different partition (or create a new meta-datasets with more classes..).

Cheers, 
Luca

**Comment by AmirooR** [comment]
OK, thanks.

Cheers,
Amir
